apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: gamebuddy
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: gamebuddy
spec:
  selector:
    app.kubernetes.io/name: backend
  ports:
    - name: api
      port: 3001
      targetPort: api
    - name: chat
      port: 4000
      targetPort: chat
